- name: Add PGDG APT key
  apt_key:
    url:  https://www.postgresql.org/media/keys/ACCC4CF8.asc
  when: postgresql_install_from_official_repo
  tags: postgresql.install

- name: Add PGDG APT repository
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main"
  when: postgresql_install_from_official_repo
  tags: postgresql.install

- name: Install PostgreSQL
  apt:
    name: postgresql-{{ postgresql_version }}
  tags: postgresql.install

- name: Install python-psycopg2 (for Ansible)
  apt:
    name: python-psycopg2
  tags: postgresql.install

- name: Create databases
  postgresql_db:
    name: "{{ item.name }}"
    template: "{{ item.template | default('') }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ postgresql_databases }}"
  become: yes
  become_user: postgres
  tags: postgresql.dbs

- name: Add users
  postgresql_user:
    name: "{{ item.name }}"
    password: "{{ item.password | default('') }}"
    db: "{{ item.db }}"
    priv: "{{ item.priv  | default('') }}"
    role_attr_flags: "{{ item.role_attr_flags | default('') }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ postgresql_users }}"
  become: yes
  become_user: postgres
  tags: postgresql.users

- name: Set postgresql options
  template:
    src: options.conf.j2
    dest: "/etc/postgresql/{{ postgresql_version }}/main/conf.d/ansible.conf"
  notify: restart postgresql
  tags: postgresql.options

- name: Enable and start postgresql service
  systemd:
    name: postgresql.service
    enabled: true
    state: started
  tags: postgresql.install
